### ISSUE TITLE
Update project layout?

### ISSUE THREAD

**Issue by TheBestPessimist** [Mamiglia/Reddit-Wallpaper#19]
Hello

I'm trying to run the code locally and the way it is now, it involves a lot of _manual_ work to make it work. 
Would you consider accepting a Pull Request where I add gradle for dependency management, and also update he folder structure a bit?

**Comment by Mamiglia** [comment]
Yes! In fact I have no experience with Maven, Gradle and such. I would really appreciate any contribution! Though as you can see right now the code doesn't work because we're in the middle of a big update and rework (I should've done this in a branch I know) so it's normal that right now the code doesn't work out of the box

**Comment by TheBestPessimist** [comment]
okay. i will try to create the simplest of gradle configurations :)

**Comment by TheBestPessimist** [comment]
also, can you give me a commit hash (from the past) where the app works successfully, so that i can try there and make sure everything works as expected?


Lastly: do you by any chance use intellij Idea? i highly suggest it!

**Comment by Mamiglia** [comment]
I just reverted the main branch to the last working commit, now all the new rework is in the branch structure-rework, so the current last commit (2 Jan 2022 104d24a02257092a055cd08d0b1b0321406d28d3) works. I do use Intellij Idea already, but it seems I can't make the best use ot it!
