### ISSUE TITLE
[FEATURE] Notifications

### ISSUE THREAD

**Issue by aTomicTurnip** [Mamiglia/Reddit-Wallpaper#26]
Would be nice if at any new walllpaper will appear a notification popup with all the main info (name, resolution, discussion link) and then fade out (like the old reddit wallpaper changer style, not the Windows standard notification)

**Comment by Mamiglia** [comment]
This is actually a very good idea, but why not windows standard notifications? It would ease some computation

**Comment by aTomicTurnip** [comment]
> This is actually a very good idea, but why not windows standard notifications? It would ease some computation

Well, it's just personal taste, I don't really like Windows notifications. But if it's easier on your work, it's fine. Maybe later in the future you can develop a nicer notification system and allow users to choose between the two

**Comment by aTomicTurnip** [comment]
> This is actually a very good idea, but why not windows standard notifications? It would ease some computation

Well, it's just personal taste, I don't really like Windows notifications. But if it's easier on your work, it's fine. Maybe later in the future you can develop a nicer notification system and allow users to choose between the two

**Comment by Mamiglia** [comment]
This feature has been implemented and will be inthe next release. 

I did implement it with custum notifications (It turns out it's actually easier!), and I don't know where else I should use this notification system, or what to do when the notification is clicked.

At the current stage a notification is sent each time the wallpaper changes (can be turned off in settings), should I use this also for communicating a change failure? 

Should I add an action when the notification is clicked? Like opening the post on Reddit? Current behaviour is that when clicked the notification goes away, and I honestly kinda like this behaviour because it looks less invasive

**Comment by aTomicTurnip** [comment]
- On click: maybe you can add in the settings the expected behaviour (like a dropdown menu that allows the user to dismiss it or opening the reddit page)
- Adding a notification for changing failure may be good, but not the cleanest way I suppose. It actually doesn't matter to me and I don't know if and how you may ask the userbase about that

**Comment by Mamiglia** [comment]
I will wait more feedbacks on this question, until then, since the current release supports this feature I'm gonna close this Issue
